export declare const VERSION = '0.1.0';
export declare const IS_WINDOWS: boolean;
export declare const IS_MACOS: boolean;
export declare const CLI_BINARY_NAME: string;
export declare const APP_BINARY_NAME: string;
export declare const SERVER_BINARY_NAME: string;
export declare const GITHUB_REPO = 'harms-haus/ymir-terminal';
export declare const YMIR_HOME_DIR_NAME = '.ymir';
export declare const DEFAULT_COLS = 80;
export declare const DEFAULT_ROWS = 24;
export declare const WS_RECONNECT_ATTEMPTS = 5;
export declare const WS_RECONNECT_BASE_DELAY_MS = 1000;
export declare const WS_RECONNECT_MAX_DELAY_MS = 16000;
export declare const CONFIG_DIR = '~/.config/ymir';
export declare const DB_FILE = 'ymir.db';
export declare const MAX_CONNECTIONS = 100;
