// ---------------------------------------------------------------------------
// Re-exports from domain modules
// ---------------------------------------------------------------------------
export * from './auth';
export * from './terminal';
export * from './workspace';
export * from './file';
export * from './git';
export * from './config';
export * from './session';
export * from './tab';
export * from './path';
// ---------------------------------------------------------------------------
// Request & event type constants
// ---------------------------------------------------------------------------
export const REQUEST_TYPES = [
  'auth',
  'terminal.create',
  'terminal.input',
  'terminal.resize',
  'terminal.close',
  'terminal.state',
  'workspace.list',
  'workspace.create',
  'workspace.update',
  'workspace.delete',
  'workspace.reorder',
  'workspace.subscribe',
  'workspace.unsubscribe',
  'file.tree',
  'file.read',
  'file.write',
  'file.delete',
  'file.rename',
  'file.create',
  'file.copy',
  'file.move',
  'file.search',
  'file.search.replace',
  'git.status',
  'git.log',
  'git.repoDiscovery',
  'git.stage',
  'git.unstage',
  'git.discard',
  'git.commit',
  'git.branches',
  'git.checkout',
  'git.push',
  'git.fetch',
  'git.diffData',
  'git.commitDetails',
  'git.commitDiff',
  'git.worktreeList',
  'git.worktreeCreate',
  'git.worktreeRemove',
  'git.worktreeMerge',
  'git.worktreeCopyFiles',
  'git.stashPush',
  'git.stashList',
  'git.stashApply',
  'git.stashPop',
  'git.stashDrop',
  'git.stashClear',
  'git.pull',
  'git.sync',
  'git.merge',
  'git.rebase',
  'git.rebaseAbort',
  'git.rebaseStatus',
  'git.commitAmend',
  'git.commitAll',
  'git.resetSoft',
  'git.stageAll',
  'git.unstageAll',
  'git.discardAll',
  'git.branchRename',
  'git.branchDelete',
  'git.branchDeleteRemote',
  'git.branchPublish',
  'git.branchesRemote',
  'git.branchCreateFrom',
  'git.remoteAdd',
  'git.remoteRemove',
  'git.remoteList',
  'path.autocomplete',
  'config.get',
  'config.set',
  'tab.list',
  'tab.create',
  'tab.update',
  'tab.delete',
  'tab.reorder',
  'tab.restore',
];
export const EVENT_TYPES = [
  'terminal.output',
  'terminal.exit',
  'file.change',
  'file.search.progress',
  'connection.status',
  'git.statusChange',
  'git.repoDiscovery.progress',
];
